# Generated by Django 6.0.6 on 2026-07-03 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('TRAVAUX', 'Travaux'), ('FOURNITURES', 'Fournitures'), ('SERVICES', 'Services')], max_length=20, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_parametre', models.CharField(max_length=100, unique=True, verbose_name='Nom du paramètre')),
                ('valeur', models.TextField(verbose_name='Valeur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=50, unique=True, verbose_name='Mot-clé')),
            ],
            options={
                'verbose_name': 'Mot-clé',
                'verbose_name_plural': 'Mots-clés',
            },
        ),
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('type', models.CharField(choices=[('ACHETEUR', 'Acheteur'), ('PRESTATAIRE', 'Prestataire')], default='ACHETEUR', max_length=20, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Organisme',
                'verbose_name_plural': 'Organismes',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('objet', models.TextField(verbose_name='Objet')),
                ('date_limite', models.DateTimeField(verbose_name='Date limite')),
                ('lieu_execution', models.CharField(blank=True, max_length=100, null=True, verbose_name="Lieu d'exécution")),
                ('budget_estime', models.CharField(blank=True, max_length=50, null=True, verbose_name='Budget estimé')),
                ('est_annule', models.BooleanField(default=False, verbose_name='Annulé')),
                ('est_informatique', models.BooleanField(default=False, verbose_name='Offre IT')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='scraper.categorie', verbose_name='Catégorie')),
                ('mots_cles', models.ManyToManyField(blank=True, related_name='consultations', to='scraper.motcle', verbose_name='Mots-clés')),
                ('acheteur', models.ForeignKey(limit_choices_to={'type': 'ACHETEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations_acheteur', to='scraper.organisme', verbose_name='Acheteur')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('destinataire', models.EmailField(max_length=254, verbose_name='Destinataire')),
                ('email_envoye', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='scraper.configuration', verbose_name='Configuration')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='scraper.consultation', verbose_name='Consultation')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scraping', models.DateTimeField(auto_now_add=True, verbose_name='Date du scraping')),
                ('nb_consultations', models.IntegerField(default=0, verbose_name='Nombre de consultations')),
                ('nb_resultats', models.IntegerField(default=0, verbose_name='Nombre de résultats')),
                ('nb_offres_it', models.IntegerField(default=0, verbose_name="Nombre d'offres IT")),
                ('statut', models.CharField(default='Succès', max_length=50, verbose_name='Statut')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques', to='scraper.configuration', verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Historique de scraping',
                'verbose_name_plural': 'Historiques de scraping',
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='mots_cles',
            field=models.ManyToManyField(blank=True, related_name='configurations', to='scraper.motcle', verbose_name='Mots-clés'),
        ),
        migrations.CreateModel(
            name='ResultatAvisAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('objet', models.TextField(verbose_name='Objet')),
                ('date_publication_resultat', models.DateTimeField(verbose_name='Date de publication du résultat')),
                ('nombre_devis', models.IntegerField(blank=True, null=True, verbose_name='Nombre de devis')),
                ('montant_ttc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Montant TTC')),
                ('est_infructueux', models.BooleanField(default=False, verbose_name='Infructueux')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='scraper.consultation', verbose_name='Consultation concernée')),
                ('prestataire', models.ForeignKey(blank=True, limit_choices_to={'type': 'PRESTATAIRE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_prestataire', to='scraper.organisme', verbose_name='Prestataire (entreprise gagnante)')),
            ],
            options={
                'verbose_name': "Résultat d'avis d'achat",
                'verbose_name_plural': "Résultats des avis d'achat",
            },
        ),
    ]
