# Generated by Django 6.0.6 on 2026-07-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_parametre', models.CharField(max_length=100, unique=True)),
                ('valeur', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('objet', models.TextField()),
                ('acheteur', models.CharField(max_length=200)),
                ('date_limite', models.DateTimeField()),
                ('lieu_execution', models.CharField(max_length=100)),
                ('budget_estime', models.CharField(blank=True, max_length=50, null=True)),
                ('est_annule', models.BooleanField(default=False)),
                ('est_informatique', models.BooleanField(default=False)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scraping', models.DateTimeField(auto_now_add=True)),
                ('nb_consultations', models.IntegerField(default=0)),
                ('nb_resultats', models.IntegerField(default=0)),
                ('nb_offres_it', models.IntegerField(default=0)),
                ('statut', models.CharField(default='Succès', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatAvisAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('objet', models.TextField()),
                ('acheteur', models.CharField(max_length=200)),
                ('date_limite', models.DateTimeField()),
                ('lieu_execution', models.CharField(max_length=100)),
                ('nombre_devis', models.IntegerField()),
                ('entreprise_attributaire', models.CharField(blank=True, max_length=200, null=True)),
                ('montant_ttc', models.CharField(blank=True, max_length=50, null=True)),
                ('est_infructueux', models.BooleanField(default=False)),
                ('date_publication_resultat', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.EmailField(max_length=254)),
                ('email_envoye', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.consultation')),
            ],
        ),
    ]
